from selenium import webdriver
from bs4 import BeautifulSoup
import time
import csv
start_url = "https://en.wikipedia.org/wiki/List_of_brightest_stars_and_other_record_stars"
browser = webdriver.Chrome("//Users/syedali/Desktop/webscraping1/chromedriver")
browser.get(start_url)
time.sleep(10)
def scrape():
    headers = ["Name", "Distance", "Mass", "Radius","Constellation","Right_ascension","Declintion","Apparent_magnitude","Spectral_type","U_B_color_index","B_V_color_index","Variable_type","Radial_velocity","Proper_motion","Parallax","Distance","Absolute magnitude"]
    planet_data = []
    for i in range(0, 428):
        soup = BeautifulSoup(browser.page_source, "html.parser")
        for ul_tag in soup.find_all("ul", attrs={"class", "Stars"}):
            li_tags = ul_tag.find_all("li")
            temp_list = []
            for index, li_tag in enumerate(li_tags):
                if index == 0:
                    temp_list.append(li_tag.find_all("a")[0].contents[0])
                else:
                    try:
                        temp_list.append(li_tag.contents[0])
                    except:
                        temp_list.append("")
            planet_data.append(temp_list)
        browser.find_element_by_xpath("").click()
    with open("scrapper_2.csv", "w") as f:
        csvwriter = csv.writer(f)
        csvwriter.writerow(headers)
        csvwriter.writerows(planet_data)
scrape()